### ISSUE TITLE
iPhone XS 12.1.2 with Unc0ver not working

### ISSUE THREAD

**Issue by riotdream** [MatthewPierson/deverser#1]
Hi,

I've got this setup:
iPhone XS on iOS 12.1.2 jb with unc0ver 3.5.6 because is SSH only and when I try to dump the boot loader I've got this error:

root@ (/var/root)# cat /dev/rdisk1 | dd of=dump.raw bs=256 count=$((0x4000))
cat: /dev/rdisk1: Operation not permitted
0+0 records in
0+0 records out
0 bytes transferred in 0.000080 secs (0 bytes/sec)

Is a problem with unc0ver?

**Comment by MatthewPierson** [comment]
What do you mean "is SSH only"? Try jailbreaking with the latest Unc0ver version, I just tried it on my 5s running 12.1.2 and the script dumped SHSH perfectly.

**Comment by riotdream** [comment]
I mean that in the Unc0ver options is flagged "SSH Only" and disabled "load tweak".

**Comment by MatthewPierson** [comment]
If you want to use this you'll need to jailbreak with "SSH Only" off and "Load Tweaks" on

**Comment by Merculous** [comment]
If I'm correct, SSH only means that the root filesystem is still read only. I'm assuming you're getting operation not permitted due to reading from /dev/rdisk1, which is out of reach if you have SSH only on. You can even read what SSH only does in unc0ver.

**Comment by riotdream** [comment]
thanks both of you for the answer.

@Merculous:
the system seems to me mounted RW either if is on "SSH Only".

> root@ (/var/root)# mount
> /dev/disk0s1s1 on / (apfs, local, journaled, noatime)
> devfs on /dev (devfs, local, nosuid, nobrowse)
> /dev/disk0s1s2 on /private/var (apfs, local, nodev, nosuid, journaled, noatime, protect)
> /dev/disk0s1s3 on /private/var/wireless/baseband_data (apfs, local, nodev, nosuid, journaled, noatime, nobrowse)
> /dev/disk0s1s4 on /private/var/hardware (apfs, local, nodev, nosuid, journaled, noatime, nobrowse)
> root@ (/var/root)# 

@MatthewPierson I can do a full jailbreak but unc0ver with substitute support (or the newer substrate) is power angry and the battery last less than a minimal jb with "ssh only" this is my main concern. I've submitted a ticket for unc0ver but is not read.

**Comment by JQ555888** [comment]
If you care that much about dumping on device shsh, just jailbreak it properly with the latest version so you'd have filesystem RW. If you think unc0ver drains your battery (with which I wholeheartedly agree being on checkra1n for way too long), use the Restore RootFS option after you have dumped the ticket -- you won't lose anything unless you've made changes to the system with ssh, which is unlikely.

This is not an issue with the script itself since all this script does is nothing but dumping a partition of several megabytes, which can be done by yourself just using the dd command on device. I don't think flagging an issue here would help as it's not the script's fault at all.

**Comment by riotdream** [comment]
I've updated unc0ver to 3.7.0-b3 for A12 on iOS 12 and all works fine.

Thanks!
